# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Start

env:
  WORKING_FOLDER: C:\test\

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      run_number:
        description: 'Run number'
        required: true


jobs:
#   prepare:
#     runs-on: asus-mz
#     steps:
#       - uses: actions/checkout@v3
#       - name: Cache node_modules
#         uses: actions/cache@v2
#         with:
#           path: node_modules
#           key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-modules-
#       - name: Install
#         run: npm i
#       - name: Build
#         run: npm run build
#       - uses: actions/upload-artifact@v3
#         with:
#           name: build
#           path: .next
  start:
    runs-on: asus-mz
    needs: prepare
    steps:
        - uses: actions/download-artifact@v3
          with:
            name: build
        - name: Stop
          run: npx kill-port 3000
        - name: Clean
          continue-on-error: true
          run: IF EXIST %WORKING_DIRECTORY% RMDIR /S /Q %WORKING_DIRECTORY%.next
        - name: Move to public folder
          run: move .next %WORKING_DIRECTORY%
        - name: Start
          working-directory: ${{ env.WORKING_FOLDER }}
          run: |
                $env:RUNNER_TRACKING_ID=""
                ./start.sh
