# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Form Applications

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: asus-mz
    steps:
      - name: Policy
        shell: cmd
        run: |
              powershell -Command "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"
              cd C:\test\
              npm i
              npm run build
              npm start
      # - name: Go to folder
      #   run: cd C:\test\
      # - name: Install
      #   run: npm i
      # - name: Build
      #   run: npm run build
      # - name: Start
      #   run: npm start
